// Treat definitions — what each treat means and how to earn it
// Treats are awarded by AI analysis of meeting transcript chunks

const TREATS = {
  apple: {
    id: 'apple',
    emoji: '🍎',
    name: 'Apple',
    color: '#E83030',
    meaning: 'Clarifying Question',
    description: 'Someone asked "what do you mean by…?" or requested an explanation',
    examples: ['What does that term mean?', 'Can you clarify that?', "I'm not sure I follow — can you explain?"],
    keywords: ['clarif', 'what do you mean', 'can you explain', 'i don\'t understand', 'what is', 'define', 'elaborate', 'help me understand'],
  },
  cake: {
    id: 'cake',
    emoji: '🎂',
    name: 'Cake',
    color: '#F0A020',
    meaning: 'Deadline / Timeline Question',
    description: 'Someone asked about timing, deadlines, or scheduling',
    examples: ['When is this due?', 'What\'s the timeline?', 'By when do we need this?'],
    keywords: ['deadline', 'timeline', 'when is', 'by when', 'due date', 'schedule', 'eta', 'how long', 'how soon'],
  },
  cookie: {
    id: 'cookie',
    emoji: '🍪',
    name: 'Cookie',
    color: '#C07020',
    meaning: 'Process / Workflow Question',
    description: 'Someone asked how something works or who owns a step',
    examples: ['How do we handle this?', 'Who is responsible for...?', 'What\'s the process for...?'],
    keywords: ['process', 'workflow', 'how do we', 'who is responsible', 'who owns', 'next steps', 'how does this work', 'procedure'],
  },
  carrot: {
    id: 'carrot',
    emoji: '🥕',
    name: 'Carrot',
    color: '#E86820',
    meaning: 'Jargon Translation',
    description: 'Someone bridged department-specific terminology for the whole group',
    examples: ['In our team we call that...', 'Just to clarify the terminology...', 'When you say X, our team means Y'],
    keywords: ['in our team', 'we call it', 'terminology', 'jargon', 'what we mean by', 'in our department', 'translation', 'in other words'],
  },
  star: {
    id: 'star',
    emoji: '⭐',
    name: 'Star',
    color: '#E8C020',
    meaning: 'Action Item Defined',
    description: 'A clear next step was captured with an owner or deadline',
    examples: ['I will take care of X by Friday', 'Action item: Sarah will...', 'Next steps: ...'],
    keywords: ['action item', 'i will', 'will take care', 'follow up', 'next step', 'by friday', 'by monday', 'assigned to', 'take this forward'],
  },
  candy: {
    id: 'candy',
    emoji: '🍬',
    name: 'Candy',
    color: '#C030C0',
    meaning: 'Cross-Team Alignment',
    description: 'Two or more departments reached agreement or found common ground',
    examples: ['That aligns with what our team needs', 'Agreed!', 'We\'re on the same page'],
    keywords: ['align', 'agreed', 'same page', 'that makes sense to both', 'we can work with that', 'perfect for us', 'works for both teams'],
  },
  blueberry: {
    id: 'blueberry',
    emoji: '🫐',
    name: 'Blueberry',
    color: '#4040C0',
    meaning: 'Follow-Up Scheduled',
    description: 'A follow-up meeting or check-in was agreed upon',
    examples: ['Let\'s meet again Thursday', 'I\'ll follow up with you', 'Let\'s sync next week'],
    keywords: ['follow up', 'let\'s meet', 'sync next', 'check in', 'circle back', 'catch up', 'schedule another', 'loop back'],
  },
  gem: {
    id: 'gem',
    emoji: '💎',
    name: 'Gem',
    color: '#30B0D0',
    meaning: 'Problem Resolved',
    description: 'A blocker or issue was solved during the meeting itself',
    examples: ['That solves it!', 'We figured it out', 'Problem solved'],
    keywords: ['solved', 'figured out', 'that works', 'resolved', 'that fixes', 'problem solved', 'no longer blocked', 'we\'ve got a solution'],
  },
};

const TREAT_ORDER = ['apple', 'cake', 'cookie', 'carrot', 'star', 'candy', 'blueberry', 'gem'];
